# Generated by Django 6.0.1 on 2026-01-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_weathersnapshot_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathersearch',
            old_name='wind_speed',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='weathersearch',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weathersearch',
            name='temperature_c',
        ),
        migrations.RemoveField(
            model_name='weathersearch',
            name='user',
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
