# Generated by Django 6.0.1 on 2026-01-07 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_wind_speed_weathersearch_temperature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathersearch',
            old_name='temperature',
            new_name='wind_speed',
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='temperature_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
