# Generated by Django 6.0.1 on 2026-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_temperature_weathersearch_wind_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersearch',
            name='firms_avg_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='firms_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
